# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FritzSkyReplacementDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FritzSkyReplacementDemo
pod 'Fritz/VisionSegmentationModel/Sky/Accurate'
pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.2.8/Giphy.podspec'
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'

end
